version: '2'

services:

    ### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            -   ~/workspace/:/var/www

    ### Workspace Utilities Container ###########################
    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_RUBY=true
                - INSTALL_PYTHON=true
                - INSTALL_XDEBUG=true
                - INSTALL_MONGO=false
                - INSTALL_NODE=true
                - INSTALL_YARN=true
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - INSTALL_V8JS_EXTENSION=false
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=true
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=8/*
                - YARN_VERSION=latest
                - TZ=UTC
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.78.10.177"
            - "dev.hettestpanel.io:10.78.10.177"
            - "dev.mercury.io:10.78.10.177"
            - "tabulation.io:192.168.0.1"
            - "websitepi.io:192.168.0.1"
            - "pibackend.io:192.168.0.1"
            - "graphql.io:192.168.0.1"
            - "mercury.test:192.168.0.1"
        ports:
            - "2222:22"
        tty: true

    ### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=true
                - INSTALL_SOAP=false
                - INSTALL_MONGO=true
                - INSTALL_ZIP_ARCHIVE=true
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - INSTALL_BCMATH=true
                - INSTALL_PHPREDIS=true
                - CODEIGNITER=false
            dockerfile: Dockerfile-73
        volumes_from:
            - applications
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.78.10.177"
            - "dev.hettestpanel.io:10.78.10.177"
            - "dev.mercury.io:10.78.10.177"
            - "tabulation.io:192.168.0.1"
            - "websitepi.io:192.168.0.1"
            - "pibackend.io:192.168.0.1"
            - "graphql.io:192.168.0.1"
            - "mercury.test:192.168.0.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG=serverName=laravel
            - PHP_XDEBUG_ENABLED = 1
            - XDEBUG_CONFIG=remote_host=10.254.254.254
    ### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - applications
        volumes:
            - ./logs/nginx/:/var/log/nginx
            - ./nginx/sites/:/etc/nginx/sites-available
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

    ### MySQL Container #########################################

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=homestead
                - MYSQL_USER=homestead
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3307:3306"

    ### MongoDB Container #######################################

    mongo:
        build: ./mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo:/data/db

    ### Redis Container #########################################

    redis:
        build: ./redis
        volumes:
            - redis:/data
        ports:
            - "6379:6379"

    ### Beanstalkd Container ####################################

    beanstalkd:
        build: ./beanstalkd
        ports:
            - "11300:11300"
        privileged: true
        links:
            - php-fpm

    ### Beanstalkd Console Container ############################

    beanstalkd-console:
        build: ./beanstalkd-console
        ports:
            - "2080:2080"
        links:
            - beanstalkd



### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    postgres:
        driver: "local"
    memcached:
        driver: "local"
    redis:
        driver: "local"
    neo4j:
        driver: "local"
    mariadb:
        driver: "local"
    mongo:
        driver: "local"
    phpmyadmin:
        driver: "local"
    aerospike:
        driver: "local"
    caddy:
        driver: "local"
    elasticsearch-data:
        driver: "local"
    elasticsearch-pkugins:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"

